export const GREET = 'GREET';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const GET_SHOWCASE_TITLES = 'GET_SHOWCASE_TITLES';
export const SHOWCASE_FETCHED = 'SHOWCASE_FETCHED';
